name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show basics
        run: |
          echo "== pwd ==" && pwd
          echo "== files ==" && ls -la
          echo "== package.json ==" && (cat package.json || true)
          echo "== vite.config.ts ==" && (cat vite.config.ts || true)

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-fund --no-audit

      - name: Show versions
        run: |
          node -v
          npm -v
          npx vite --version || true

      - name: Build (npm script or fallback to npx)
        run: |
          if npm run -s build; then
            echo "Built via npm script"
          else
            echo "npm run build failed, trying npx vite build..."
            npx --yes vite@5.4.8 build --base=/MixMyFace/
          fi

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
