name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: finddir
        run: |
          set -e
          D=$(git ls-files | grep -E '^([^/]+/)*package\.json$' | head -n1 || true)
          if [ -z "$D" ]; then
            exit 1
          fi
          DIR=$(dirname "$D")
          if [ "$DIR" = "." ]; then DIR=""; fi
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        working-directory: ${{ steps.finddir.outputs.dir }}
        run: npm install --no-fund --no-audit

      - name: Build
        working-directory: ${{ steps.finddir.outputs.dir }}
        run: |
          if npm run -s build; then
            echo done
          else
            npx --yes vite@5.4.8 build --base=/MixMyFace/
          fi

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.finddir.outputs.dir }}dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
